###
POST http://localhost:8080/api/v0_01/category/add
Content-Type: application/json

{
  "categoryName": "Bisexual"
}

###
GET http://localhost:8080/api/v0_01/category/1

###
GET http://localhost:8080/api/v0_01/category/full/1

###
GET http://localhost:8080/api/v0_01/category

###
DELETE http://localhost:8080/api/v0_01/category/delete/1

###
PUT http://localhost:8080/api/v0_01/category/update/8
Content-Type: application/json

{
  "categoryName" : "PanzerSexual"
}

###



